nameOverride: ""
fullnameOverride: ""
namespaces:
  - name: gitops-apps
domain: ''
argocd:
  plugin:
    version: "1.17.0"
    AVP_K8S_ROLE: argocd
    AVP_TYPE: k8s
    VAULT_ADDR: 'http://vault.vault.svc:8200'
    AVP_AUTH_TYPE: 'http://vault.vault.svc:8200'
    VAULT_SKIP_VERIFY: "true"
  initialRepositories: |
    - name: day-2
      url: https://github.com/PF-POC/day-1-gitops.git
      insecure: true
      usernameSecret:
        name: repository-secret
        key: username
      passwordSecret:
        name: repository-secret
        key: password
    - name: day-2
      type: git
      project: default
      url: https://github.com/PF-POC/day-2-gitops.git
      insecure: true
      usernameSecret:
        name: repository-secret
        key: username
      passwordSecret:
        name: repository-secret
        key: password   
    - name: helm-charts
      project: default
      type: helm
      url: https://pf-poc.github.io/helm-repository
  applications:
  - name: d1
    annotations:
    helmRepoUrl: https://pf-poc.github.io/helm-repository
    chart: gitops-payload
    targetRevision: 1.1.3
    gitRepoUrl: https://github.com/PF-POC/day-2-gitops.git
    gitPath: ''