{{ range $applications := .Values.applications -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $applications.name }}
  namespace: {{ $applications.teamName }}-team
  annotations:
    argocd.argoproj.io/sync-wave: {{ $applications.syncWave | default $defaults.syncWave | quote }}
spec:
  destination:
    namespace: {{ $applications.teamName }}-team
    server: https://kubernetes.default.svc
  project: {{ $applications.teamName }}-project
  sources:
    - repoURL: {{ $applications.helmRepoUrl }}
      chart: {{ $applications.chart }}
      targetRevision: '{{ $applications.targetRevision }}'
      path: charts
      helm:
        valueFiles:
        - $values/{{ $applications.gitPath }}
        values: |
          teamName: {{ $applications.teamName }}
    - repoURL: {{ $applications.gitRepoUrl }}
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
---
{{- end }}
