{{ range $applications := .Values.applications -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: openshift-gitops
  annotations:
    helm.sh/hook: post-install
  {{- range $key, $value := $applications.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "{{ $applications.gitUrl }}"
    targetRevision: 0.0.1
    path: {{ $.Values.gitops_path }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
---
{{- end }}

# {{ range $applications := .Values.applications -}}
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: {{ .name }}
#   namespace: openshift-gitops
#   annotations:
#     helm.sh/hook: post-install
#   {{- range $key, $value := $applications.annotations }}
#     {{ $key }}: {{ $value | quote }}
#   {{- end }}
# spec:
#   destination:
#     namespace: openshift-gitops
#     server: https://kubernetes.default.svc
#   project: default
#   sources:
#     - repoURL: https://AB-POC.github.io/helm-charts/
#       chart: gitops-infra-payload
#       targetRevision: 0.0.2
#       path: /charts
#       helm:
#         valueFiles:
#         - $values/{{ $.Values.gitops_path }}
#     - repoURL: {{ $applications.gitUrl }}
#       targetRevision: HEAD
#       ref: values
#   syncPolicy:
#     automated:
#       prune: false
#       selfHeal: true
#     syncOptions:
#     - ApplyOutOfSyncOnly=true
# ---
# {{- end }}