apiVersion: ecr.mobb.redhat.com/v1alpha1
kind: ArgoHelmRepoSecret
metadata:
  name: helm-repo
  namespace: openshift-gitops
spec:
  generated_secret_name: ecr-argo-helm-secret
  url: "{{ .Values.ecrAwsAccount }}.dkr.ap-southeast-2.amazonaws.com"
  frequency: 4h
  region: ap-southeast-2
---
apiVersion: ecr.mobb.redhat.com/v1alpha1
kind: Secret
metadata:
  name: ecr-secret
  namespace: openshift-gitops
spec:
  generated_secret_name: ecr-docker-secret
  ecr_registry: "{{ .Values.ecrAwsAccount }}.dkr.ap-southeast-2.amazonaws.com"
  frequency: 4h
  region: ap-southeast-2
---
