defaults:
  helmRepo: https://pf-poc.github.io/helm-repository
  path: ''
  name: day-one
  server: https://kubernetes.default.svc
  syncWave: 0
  AVP_K8S_ROLE: argocd
  AVP_TYPE: k8s
  VAULT_ADDR: 'http://vault.vault.svc:8200'
  AVP_AUTH_TYPE: 'http://vault.vault.svc:8200'
  VAULT_SKIP_VERIFY: "true"

infrastructure:
  - name: cluster-logging
    namespace: openshift-logging
    chart: cluster-logging
    targetRevision: "0.0.3"
    mount_path: "kv/data/vplugin/supersecret"
    annotations:
      sync: 56
    syncWave: 50
    values:
      splunkHecToken: bla
      splunURL: bla