{{ $team := .Values.team -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "main-app-project"
  namespace: {{ .Values.gitopsNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "{{ $team.name }} users deployment apps"
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
