{{ range $applicationTeams := .Values.applicationTeams -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $applicationTeams.teamName }}-team
  {{- if $ns.annotations }}
  annotations:
    {{- toYaml $ns.annotations | trimPrefix "|" | indent 2 }}
  {{ end }}
  labels:
  {{- if $ns.labels }}
    {{- toYaml $ns.labels | trimPrefix "|" | indent 2 }}
  {{ end }}
{{ end -}}

