ldapUrl: placeholder-ldapUrl # ldaps://ldapserver.example.com:636
ldapCert: placeholder-ldapCert # PEM Encoded certificate(s)
bindDN: "cn=Directory Manager"
bindPassword: placeholder-bindPassword # string
ldapPort: 1389
ldapsPort: 1636
ldapBindPassword: p@55w0rd
ldapSuffix: "dc=ldap,dc=example,dc=com"
ldapUsersPassword: password