nameOverride: ""
fullnameOverride: ""
namespaces:
  - name: openshift-gitops
subscriptions:
  - name: openshift-gitops-operator
    namespace: openshift-operators
    channel: latest
    config:
      env:
      - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
        value: "true"
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: d2-application-gitops,openshift-gitops
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
operatorGroups:
catalogSources: []
  # - name: operatorhubio
  #   sourceType: grpc
  #   image: quay.io/operator-framework/upstream-community-operators:latest
  #   displayName: Community Operators
  #   publisher: OperatorHub.io
argocd:
  plugin:
    version: "1.17.0"
    AVP_K8S_ROLE: argocd
    AVP_TYPE: vault
    VAULT_ADDR: 'http://vault.vault.svc:8200'
    AVP_AUTH_TYPE: k8s
    VAULT_SKIP_VERIFY: "true"
  initialRepositories: |
    - name: day-2
      url: https://github.com/PF-POC/day-1-gitops.git
      insecure: true
      usernameSecret:
        name: repository-secret
        key: username
      passwordSecret:
        name: repository-secret
        key: password
    - name: day-2
      type: git
      project: default
      url: https://github.com/PF-POC/day-2-gitops.git
      insecure: true
      usernameSecret:
        name: repository-secret
        key: username
      passwordSecret:
        name: repository-secret
        key: password   
    - name: helm-charts
      project: default
      type: helm
      url: https://pf-poc.github.io/helm-repository
  applications:
  - name: d1
    annotations:
    helmRepoUrl: https://pf-poc.github.io/helm-repository
    chart: gitops-payload
    targetRevision: 1.1.4
    gitRepoUrl: https://github.com/PF-POC/day-1-gitops.git
    gitPath: ''
    adGroup: PFAUTHAD
    repositories: 
    - https://github.com/PF-POC/day-1-gitops.git
    - https://github.com/PF-POC/day-2-gitops.git
    - https://pf-poc.github.io/helm-repository
  - name: d2
    annotations:
    helmRepoUrl: https://pf-poc.github.io/helm-repository
    chart: gitops-payload
    targetRevision: 1.1.4
    gitRepoUrl: https://github.com/PF-POC/day-2-gitops.git
    gitPath: ''
    adGroup: PFAUTHAD
    repositories: 
    - https://github.com/PF-POC/day-1-gitops.git
    - https://github.com/PF-POC/day-2-gitops.git
    - https://pf-poc.github.io/helm-repository