{{ $plugin := .Values.argocd.plugin -}}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: post-install
  name: vault-configuration
  namespace: gitops-apps
stringData:
  AVP_TYPE: $plugin.AVP_TYPE
  AVP_AUTH_TYPE: $plugin.AVP_AUTH_TYPE
  AVP_K8S_ROLE: $plugin.VP_K8S_ROLE
  VAULT_ADDR: $plugin.AULT_ADDR
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: regcred
metadata:
  name: vplugin
  namespace: gitops-apps
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoicmhfZWVfcGFmb3N0ZXIiLCJwYXNzd29yZCI6IkppbWJvOTU3OEBNYXJjQCIsImVtYWlsIjoicm9vdEBtYWlsLmNvbSIsImF1dGgiOiJjbWhmWldWZmNHRm1iM04wWlhJNlNtbHRZbTg1TlRjNFFFMWhjbU5BIn19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: gitops-apps
type: kubernetes.io/dockerconfigjson