apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  annotations:
    helm.sh/hook: post-install
  name: instance
  namespace: openshift-logging
spec:
  collection:
    logs:
        type: vector
  managementState: Managed