apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mycert
spec:
  isCA: false
  commonName: api.business.com
  secretName: mycert
  dnsNames:
  - api.business.com
  issuerRef:
    name: vault-issuer
    kind: Issuer