apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/business-dot-com
    server: http://d1-vault-dev-vault.d1-vault-dev.svc.cluster.local:8200
    auth:
      kubernetes:
        role: vault-issuer-role
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer
          audiences: ["https://kubernetes.default.svc","vault://cert-test/vault-issuer"]


