apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: {{ .Values.path }} 
    server: {{ .Values.server }} 
    auth:
      kubernetes:
        role: vault-issuer-role
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer

