---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: "{{ .Vales.namespace }}"
  annotations:
    avp.kubernetes.io/path: "kv/data/vplugin/supersecret"
type: Opaque
stringData:
  username: <username>
  password: <password>
