apiVersion: v1
kind: ConfigMap
metadata:
  name: rhds-init
  namespace: {{ .Values.namespace }}
data:
  entrypoint.sh: |-
    #!/bin/bash

    mkdir -p /tmp/rhds/bin
    export PATH=/tmp/rhds/bin:$PATH
    dscreate ds-root /tmp/rhds/bin/dsroot /tmp/rhds/bin
    hash -r dscreate

    dscreate from-file /tmp/rhds/config/rhds.ini
    cat /tmp/rhds/ldif/01-OUs.ldif |ldapadd -D "{{ .Values.bindDN }}" -w {{ .Values.ldapBindPassword }} -p {{ .Values.ldapPort }} -h ${pod_ip} -x
    cat /tmp/rhds/ldif/02-users.ldif |ldapadd -D "{{ .Values.bindDN }}" -w {{ .Values.ldapBindPassword }} -p {{ .Values.ldapPort }} -h ${pod_ip} -x
    cat /tmp/rhds/ldif/03-groups.ldif |ldapadd -D "{{ .Values.bindDN }}" -w {{ .Values.ldapBindPassword }} -p {{ .Values.ldapPort }} -h ${pod_ip} -x
    cat /tmp/rhds/ldif/04-passwords.ldif |ldapmodify -D "{{ .Values.bindDN }}" -w {{ .Values.ldapBindPassword }} -p {{ .Values.ldapPort }} -h ${pod_ip} -x
    tail -f /tmp/rhds/bin/dsroot/var/log/dirsrv/slapd-slapd/security
immutable: true