---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-group-sync
  namespace: {{ .Values.namespace }}
data:
  sync.yaml: |
    kind: LDAPSyncConfig
    apiVersion: v1
    url: "{{ .Values.ldapUrl }}"
    bindDN: "cn=Directory Manager"
    bindPassword:
      file: /etc/secrets/bindPassword
    insecure: false
    ca: /etc/ldap-ca/ca.crt
    rfc2307:
        groupsQuery:
            baseDN: "ou=Groups,{{ .Values.searchDN }}"
            scope: sub
            filter: "{{ .Values.groupFilter }}"
            derefAliases: never
            pageSize: 0
        groupUIDAttribute: cn
        groupNameAttributes: [ cn ]
        groupMembershipAttributes: [ uniqueMember ]
        usersQuery:
            baseDN: "ou=People,{{ .Values.searchDN }}"
            scope: sub
            derefAliases: never
            pageSize: 0
        userUIDAttribute: dn
        userNameAttributes: [ mail ]
---