apiVersion: v1
kind: Secret
metadata:
  name: ghcr
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJibkpsYVd4c2VTMXlhRzQ2WjJod1gyeDRWbnAwWmpCNVVtbDRNVlZIWjJwcGNqbDZkWGRzV1RaclFUQnRjakZ6TUc5aFZRPT0iCgkJfQoJfQp9