kind: ServiceAccount
apiVersion: v1
metadata:
  name: slapd-ldap
  namespace: {{ .Values.namespace }}
secrets:
  - name: ghcr-docker-cfg
imagePullSecrets:
  - name: ghcr-docker-cfg
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: slapd-ldap
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: slapd-ldap
subjects:
- kind: ServiceAccount
  name: slapd-ldap