nameOverride: ""
fullnameOverride: ""
RoleArn: placeholder
rosaClusterName: placeholder
region: placeholder
# dependency chart helper-operator
helper-operator:
  operators:
    cluster-logging:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-logging
        create: false
      subscription:
        channel: latest
        approval: Automatic
        operatorName: cluster-logging
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        config:
          env:
          - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
            value: "true"
          - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
            value: d2-application-gitops,openshift-gitops
      operatorgroup:
        enabled: false
# dependency chart helper-status-checker
helper-status-checker:
  enabled: true
  checks:
    - operatorName: cluster-logging
      namespace:
        name: openshift-logging
      syncwave: 3
      serviceAccount:
        name: "openshift-operators-install-check"