{{ $repos := $applications.repositories -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "main-app-project"
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "{{ .Values.teamName }} users project"
  sourceRepos:
  {{- range $repos }}
    - {{ . | quote }}
  {{- end }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: "gitops-apps"
      server: "https://kubernetes.default.svc"
  roles:
    - name: users
      description: "Application teams privilleges for project {{ .Values.teamName }}--users"
      policies:
        - "p, proj:{{ .Values.teamName }}-users:users, applications, *, {{ .Values.teamName }}-users/*, allow"
      groups:
        - "{{ $applications.adGroup }}"
    # - name: users-deny
    #   description: "Application teams privilleges for project `{{ .Values.teamName }}--users`"
    #   policies:
    #     - "p, proj:{{ .Values.teamName }}-users:users, applications, *, {{ .Values.teamName}}, deny"
    #   groups:
    #     - "{{ $defaults.adGroup }}"
    # - name: admin 
    #   description: "admin privilleges for project `{{ .Values.teamName }}-users`"
    #   policies:
    #     - "p, proj:{{ .Values.teamName }}-users:admin, applications, *, {{ .Values.teamName}}-admin/*, allow"
    #     - "p, proj:{{ .Values.teamName }}-users:admin, teams, get, {{ .Values.teamName }}--admin, allow"
    #   groups:
    #     - "{{ $defaults.server }}"