{{ range $applications := .Values.applications -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ $applications.name }}-project"
  namespace: {{ $applications.gitopsNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "{{ $applications.name }} users project"
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
{{- end }}