{{ range $applications := .Values.applications -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: gitops-apps
  annotations:
    helm.sh/hook: post-install
  {{- range $key, $value := $applications.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  destination:
    namespace: gitops-apps
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: {{ $applications.helmRepoURrl }}
      chart: {{ $applications.chart }}
      targetRevision: {{ $applications.targetRevision }}
      path: /charts
      helm:
        valueFiles:
        - $values/{{ $applications.gitPath }}
        values: |
          appTeam: $applications.name
    - repoURL: {{ $applications.gitRepoUrl }}
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
---
{{- end }}