{{ $plugin := .Values.argocd.plugin -}}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: post-install
  name: vault-configuration
  namespace: gitops-apps
stringData:
  AVP_TYPE: $plugin.AVP_TYPE
  AVP_AUTH_TYPE: $plugin.AVP_AUTH_TYPE
  AVP_K8S_ROLE: $plugin.VP_K8S_ROLE
  VAULT_ADDR: $plugin.AULT_ADDR
type: Opaque
