apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocds.argoproj.io/name: gitops-apps
    argocds.argoproj.io/namespace: gitops-apps
  labels:
    app.kubernetes.io/managed-by: gitops-apps
    app.kubernetes.io/name: gitops-apps
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-argocd-application-controller-gitops-apps
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - list
