---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: ldap-group-sync
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cronSchedule |quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccount: ldap-group-sync
          serviceAccountName: ldap-group-sync
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: "ldap-sync-volume"
              configMap:
                name: "ldap-group-sync"
            - name: "ldap-bind-secret"
              secret:
                secretName: "ldap-bind-secret"
            {{ if eq .Values.insecure "false" }}
            - name: "ldap-ca"
              configMap:
                name: "ldap-ca"
            {{ end }}
          containers:
            - name: ldap-sync
              resources:
                limits:
                  memory: 1Gi
                  cpu: 1
                requests:
                  memory: 1Gi
                  cpu: 1
              image: "registry.redhat.io/openshift4/ose-cli:latest"
              command:
                - "/bin/bash"
                - "-c"
                - "oc adm groups sync --sync-config=/etc/config/sync.yaml --confirm"
              volumeMounts:
                - mountPath: "/etc/config"
                  name: "ldap-sync-volume"
                - mountPath: "/etc/secrets"
                  name: "ldap-bind-secret"
                {{ if eq .Values.insecure "false" }}
                - mountPath: "/etc/ldap-ca"
                  name: "ldap-ca"
                {{ end }}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
---