# teamName: main

# defaults:
#   gitopsNamespace: d2-application-gitops
#   helmRepoUrl: https://pf-poc.github.io/helm-repository
#   path: charts
#   name: d2
#   server: https://kubernetes.default.svc
#   syncWave: 0

# infrastructure:
#   - name: gitops-app-team-config
#     chart: gitops-app-team-config
#     targetRevision: "1.0.4"
#     annotations:
#       sync: 56
#     syncWave: 50
#     values:
#       applications:
#       - name: payments
#         annotations:
#         gitopsNamespace: application-gitops
#         helmRepoUrl: https://PF-POC.github.io/helm-charts
#         chart: gitops-payload
#         targetRevision: 1.2.3
#         gitRepoUrl: https://github.com/PF-POC/day-2-gitops.git
#         gitPath: Clusters/non-prod/high-trust/rosa-pub-1/applications.yaml
#         adGroup: PFAUTHAD
#         repos: 
#         - https://github.com/PF-POC/day-1-gitops.git
#         - https://PF-POC.github.io/helm-charts
