# teamName: PFA

# defaults:
#   gitopsNamespace: gitops-apps
#   adGroup: PFAUTHAD
#   helmRepoUrl: https://pf-poc.github.io/helm-repository
#   gitRepoUrl: ""
#   path: charts
#   server: https://kubernetes.default.svc
#   syncWave: 0
#   AVP_K8S_ROLE: argocd
#   AVP_TYPE: vault
#   VAULT_ADDR: 'http://vault.vault.svc:8200'
#   AVP_AUTH_TYPE: k8s
#   VAULT_SKIP_VERIFY: "true"
#   namespaceChart: namespaces
#   namespaceChartRevision: 1.0.1
#   repositories:
#     - https://pf-poc.github.io/helm-repository

# infrastructure:
#   - name: cluster-logging
#     namespace: openshift-logging
#     chart: cluster-logging
#     targetRevision: "0.0.3"
#     annotations:
#       sync: 56
#     syncWave: 50
#     values:
#       splunkHecToken: bla
#       splunURL: bla

# namespaces: # microenvironments
#   - name: ob
#     requests:
#       cpu: 30
#       memory: 22Gi
#     limits:
#       cpu: 30
#       memory: 22Gi
#     environments: 
#       - name: dev
#         labels: |
#           name: ob-dev
#           argocd.argoproj.io/managed-by: openshift-gitops
#         applications: # microservices
#           - name: adservice
#             type: "helm-git"
#             gitRepoUrl: git@github.com:redhat-blackbelt-online-boutique/online-boutique-cd.git
#             targetRevision: HEAD
#             path: app
#             values:
#               chartname: microservice-base
#               chartRevision: 1.0.0
#           - name: cluster-logging
#             type: "helm"
#             plugin: "true"
#             targetRevision: "0.0.3"
#             chart: cluster-logging
#             values:
#               splunkHecToken: bla
#               splunURL: bla