teamName: PFA

defaults:
  gitopsNamespace: d2-application-gitops
  adGroup: PFAUTHAD
  helmRepoUrl: https://pf-poc.github.io/helm-repository
  gitRepoUrl: ""
  path: charts
  server: https://kubernetes.default.svc
  syncWave: 0
  namespaceChart: namespaces
  namespaceChartRevision: 1.0.1
  repositories:
    - https://pf-poc.github.io/helm-repository


namespaces: 
  - name: ob
    requests:
      cpu: 30
      memory: 22Gi
    limits:
      cpu: 30
      memory: 22Gi
    environments: 
      - name: dev
        labels: |
          name: ob-dev
          argocd.argoproj.io/managed-by: openshift-gitops
        applications: 
          - name: adservice
            type: "helm-git"
            gitRepoUrl: git@github.com:redhat-blackbelt-online-boutique/online-boutique-cd.git
            targetRevision: HEAD
            path: app
            values:
              chartname: microservice-base
              chartRevision: 1.0.0
              